import fs from "fs";
import { geoCentroid, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import { createStateProjection } from "../src/utils/geo.ts";

const state = JSON.parse(fs.readFileSync("public/maps/california-state.topojson", "utf8"));
const cities = JSON.parse(fs.readFileSync("public/maps/california-cities.geojson", "utf8"));
const stateFc = feature(state, state.objects.state);
const stateFeature = stateFc.features[0];

const w = 268;
const h = 118;
const proj = createStateProjection(w, h, stateFc);
const pathGen = geoPath(proj);

const ids = ["los-angeles-ca", "san-francisco-ca", "san-diego-ca"];
for (const id of ids) {
  const f = cities.features.find((x) => x.properties.id === id);
  const p = proj(geoCentroid(f));
  console.log(`${f.properties.name}: ${Math.round(p[0])}, ${Math.round(p[1])}`);
}

const d = pathGen(stateFeature);
console.log("PATH:", d);

import { writeFileSync } from "fs";
const ts = `/** Generated by scripts/onboarding-ca-path.mjs — do not hand-edit. */
export const CA_ONBOARDING_MAP = {
  width: ${w},
  height: ${h},
  statePath: ${JSON.stringify(d)},
  cities: {
    la: { x: 140, y: 96, label: "Los Angeles" },
    sf: { x: 101, y: 53, label: "San Francisco" },
    sd: { x: 153, y: 111, label: "San Diego" },
  },
} as const;
`;
writeFileSync("src/components/onboarding/californiaMapArt.ts", ts);
console.log("Wrote src/components/onboarding/californiaMapArt.ts");
